language: php

sudo: false
dist: trusty

# Active PHP versions
php:
  - 8.2

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update --prefer-dist

script: vendor/bin/phpunit -c phpunit.xml.dist
